# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # `boot` and `fileSystems` are wrapped in a single attrset rather than
  # assigned attribute by attribute: that is how the generated file reads, but
  # statix flags the repeated top-level keys (this is also how
  # hosts/grajpap/hardware-configuration.nix is written).
  boot = {
    initrd.availableKernelModules = ["xhci_pci" "ahci" "sd_mod" "rtsx_pci_sdmmc"];
    initrd.kernelModules = [];
    kernelModules = ["kvm-intel"];
    extraModulePackages = [];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/4034c528-1fe8-47fa-8ba3-5f846f07c8d2";
      fsType = "ext4";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/BE63-647E";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/496e2c39-9840-4168-a29f-d684ed5951e1";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
