{
  pkgs,
  lib,
  inputs,
  ...
}: let
  spicePkgs = inputs.spicetify-nix.legacyPackages.${pkgs.stdenv.hostPlatform.system};
  spicetifyCli = pkgs.spicetify-cli.overrideAttrs (old: {
    nativeBuildInputs = (old.nativeBuildInputs or []) ++ [pkgs.esbuild];
    postBuild =
      (old.postBuild or "")
      + ''
        mkdir -p jsHelper
        esbuild src/jsHelper/spicetifyWrapper/index.js \
          --bundle \
          --format=iife \
          --legal-comments=none \
          --minify \
          --outfile=jsHelper/spicetifyWrapper.js \
          --target=chrome108 \
          --banner:js='/* Generated by scripts/build-wrapper.mjs. Do not edit directly. */'
      '';
    postInstall =
      (old.postInstall or "")
      + ''
        chmod u+w "$out/share/spicetify/jsHelper"
        install -Dm644 jsHelper/spicetifyWrapper.js \
          "$out/share/spicetify/jsHelper/spicetifyWrapper.js"
      '';
  });
in {
  security.polkit.extraConfig = ''
    polkit.addRule(function(action, subject) {
      var allowedActions = [
        "org.freedesktop.udisks2.filesystem-mount",
        "org.freedesktop.udisks2.filesystem-mount-system",
        "org.freedesktop.udisks2.filesystem-mount-other-seat",
        "org.freedesktop.udisks2.eject-media",
        "org.freedesktop.udisks2.power-off-drive"
      ];

      if (
        allowedActions.indexOf(action.id) >= 0 &&
        subject.active &&
        subject.local &&
        (subject.isInGroup("wheel") || subject.isInGroup("storage"))
      ) {
        return polkit.Result.YES;
      }

      var agentUnits = [
        "collect-system-health.service",
        "restic-backups-nextcloud.service",
        "restic-backups-nextcloud-storage.service",
        "restic-nextcloud-restore-test.service",
        "t3code-nh-clean.service",
        "t3code-os-switch.service"
      ];

      if (
        action.id == "org.freedesktop.systemd1.manage-units" &&
        agentUnits.indexOf(action.lookup("unit")) >= 0 &&
        ["start", "restart"].indexOf(action.lookup("verb")) >= 0 &&
        subject.active &&
        subject.local &&
        subject.user == "grajpap"
      ) {
        return polkit.Result.YES;
      }
    });
  '';

  services = {
    dbus.enable = true;
    journald.extraConfig = ''
      SystemMaxUse=250M
      RuntimeMaxUse=50M
      MaxRetentionSec=7day
    '';
    psd = {
      enable = true;
      resyncTimer = "10m";
    };
  };
  programs = {
    ydotool.enable = true;
    spicetify = {
      enable = true;
      wayland = true;
      spicetifyPackage = spicetifyCli;
      theme = lib.mkForce spicePkgs.themes.catppuccin;
      colorScheme = lib.mkForce "mocha";
      # Keep executable injections minimal. Spotify updates independently, and
      # stale extensions or custom apps can leave its frontend unresponsive.
    };

    fuse.userAllowOther = true;
    java = {
      enable = true;
      package = pkgs.jre;
    };

    nix-ld.enable = true;

    bash.promptInit = ''eval "$(${pkgs.starship}/bin/starship init bash)"'';
  };

  environment.variables = {
    EDITOR = "code";
    BROWSER = "helium";
  };
  environment.systemPackages = with pkgs; [
    git
    uutils-coreutils-noprefix
    appimage-run
    starship
    wine
    winetricks
    innoextract
  ];

  time = {
    timeZone = "Europe/Warsaw";
    hardwareClockInLocalTime = true;
  };

  services.timesyncd = {
    enable = true;
    settings = {
      Time = {
        PollIntervalMinSec = 32;
        PollIntervalMaxSec = 64;
        ConnectionRetrySec = 5;
      };
    };
  };

  i18n = let
    defaultLocale = "en_US.UTF-8";
    pl = "pl_PL.UTF-8";
  in {
    inherit defaultLocale;
    extraLocaleSettings = {
      LANG = defaultLocale;
      LC_COLLATE = defaultLocale;
      LC_CTYPE = defaultLocale;
      LC_MESSAGES = defaultLocale;

      LC_ADDRESS = pl;
      LC_IDENTIFICATION = pl;
      LC_MEASUREMENT = pl;
      LC_MONETARY = pl;
      LC_NAME = pl;
      LC_NUMERIC = pl;
      LC_PAPER = pl;
      LC_TELEPHONE = pl;
      LC_TIME = pl;
    };
  };

  console = let
    variant = "u24n";
  in {
    font = "${pkgs.terminus_font}/share/consolefonts/ter-${variant}.psf.gz";
    earlySetup = true;
    keyMap = "pl";
  };

  boot.binfmt.registrations = lib.genAttrs ["appimage" "AppImage"] (ext: {
    recognitionType = "extension";
    magicOrExtension = ext;
    interpreter = "/run/current-system/sw/bin/appimage-run";
  });

  systemd = {
    services = {
      t3code-nh-clean = {
        description = "Clean old Nix generations without interactive elevation";
        path = with pkgs; [nh nix];
        serviceConfig.Type = "oneshot";
        script = ''
          exec nh clean all --keep 3
        '';
      };
      t3code-os-switch = {
        description = "Validate and apply /etc/nixos for the local coding agent";
        restartIfChanged = false;
        path = with pkgs; [git nix nix-output-monitor util-linux];
        serviceConfig = {
          Type = "oneshot";
          WorkingDirectory = "/etc/nixos";
        };
        script = ''
          set -euo pipefail

          as_user=(runuser -u grajpap -- env HOME=/home/grajpap USER=grajpap LOGNAME=grajpap)
          "''${as_user[@]}" nix flake check
          candidate="$("''${as_user[@]}" nix build \
            .#nixosConfigurations.grajpap.config.system.build.toplevel \
            --no-link \
            --print-out-paths)"

          case "$candidate" in
            /nix/store/*-nixos-system-grajpap-*) ;;
            *)
              echo "Refusing unexpected system path: $candidate" >&2
              exit 1
              ;;
          esac

          nix-env --profile /nix/var/nix/profiles/system --set "$candidate"
          exec "$candidate/bin/switch-to-configuration" boot
        '';
      };
      "getty@tty1".enable = false;
      "autovt@tty1".enable = false;
      "getty@tty7".enable = false;
      "autovt@tty7".enable = false;
    };
    user = {
      services.psd.wantedBy = lib.mkForce [];
      timers.psd-delayed-start = {
        description = "Start profile-sync-daemon after session startup";
        timerConfig = {
          OnStartupSec = "20s";
          Unit = "psd.service";
        };
        wantedBy = ["timers.target"];
      };
    };
    # Systemd OOMd
    # Fedora enables these options by default. See the 10-oomd-* files here:
    # https://src.fedoraproject.org/rpms/systemd/tree/acb90c49c42276b06375a66c73673ac3510255
    oomd.enableRootSlice = true;

    # Some legacy Nix commands still expect the root per-user profile path.
    tmpfiles.rules = [
      "D /nix/var/nix/profiles/per-user/root 755 root root - -"
    ];
  };
}
